services:
  - type: web
    name: pm-frontend
    runtime: node
    plan: starter
    buildCommand: NODE_OPTIONS=--max-old-space-size=4096 npm ci && NODE_OPTIONS=--max-old-space-size=4096 npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NITRO_PRESET
        value: node-server
      - key: NODE_ENV
        value: production
