/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalNotificationsRouteImport } from './routes/portal.notifications'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin.customers.$customerId'
import { Route as AdminCustomersNewRouteImport } from './routes/admin.customers.new'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin.projects.index'
import { Route as AdminProjectsProjectIdRouteImport } from './routes/admin.projects.$projectId'
import { Route as AdminProjectsNewRouteImport } from './routes/admin.projects.new'
import { Route as AdminTicketsIndexRouteImport } from './routes/admin.tickets.index'
import { Route as AdminTicketsTicketIdRouteImport } from './routes/admin.tickets.$ticketId'
import { Route as AdminTicketsNewRouteImport } from './routes/admin.tickets.new'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminUsersNewRouteImport } from './routes/admin.users.new'
import { Route as PortalProjectsIndexRouteImport } from './routes/portal.projects.index'
import { Route as PortalProjectsProjectIdRouteImport } from './routes/portal.projects.$projectId'
import { Route as PortalTicketsIndexRouteImport } from './routes/portal.tickets.index'
import { Route as PortalTicketsTicketIdRouteImport } from './routes/portal.tickets.$ticketId'
import { Route as PortalTicketsNewRouteImport } from './routes/portal.tickets.new'
import { Route as AdminCustomersCustomerIdEditRouteImport } from './routes/admin.customers.$customerId.edit'
import { Route as AdminProjectsProjectIdEditRouteImport } from './routes/admin.projects.$projectId.edit'
import { Route as AdminProjectsProjectIdMembersRouteImport } from './routes/admin.projects.$projectId.members'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/admin.users.$userId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/portal/notifications',
  path: '/portal/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/admin/customers/',
  path: '/admin/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/admin/customers/$customerId',
    path: '/admin/customers/$customerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCustomersNewRoute = AdminCustomersNewRouteImport.update({
  id: '/admin/customers/new',
  path: '/admin/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsProjectIdRoute = AdminProjectsProjectIdRouteImport.update({
  id: '/admin/projects/$projectId',
  path: '/admin/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/admin/projects/new',
  path: '/admin/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsIndexRoute = AdminTicketsIndexRouteImport.update({
  id: '/admin/tickets/',
  path: '/admin/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsTicketIdRoute = AdminTicketsTicketIdRouteImport.update({
  id: '/admin/tickets/$ticketId',
  path: '/admin/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsNewRoute = AdminTicketsNewRouteImport.update({
  id: '/admin/tickets/new',
  path: '/admin/tickets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/admin/users/new',
  path: '/admin/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProjectsIndexRoute = PortalProjectsIndexRouteImport.update({
  id: '/portal/projects/',
  path: '/portal/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProjectsProjectIdRoute = PortalProjectsProjectIdRouteImport.update({
  id: '/portal/projects/$projectId',
  path: '/portal/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTicketsIndexRoute = PortalTicketsIndexRouteImport.update({
  id: '/portal/tickets/',
  path: '/portal/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTicketsTicketIdRoute = PortalTicketsTicketIdRouteImport.update({
  id: '/portal/tickets/$ticketId',
  path: '/portal/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTicketsNewRoute = PortalTicketsNewRouteImport.update({
  id: '/portal/tickets/new',
  path: '/portal/tickets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersCustomerIdEditRoute =
  AdminCustomersCustomerIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminCustomersCustomerIdRoute,
  } as any)
const AdminProjectsProjectIdEditRoute =
  AdminProjectsProjectIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminProjectsProjectIdRoute,
  } as any)
const AdminProjectsProjectIdMembersRoute =
  AdminProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminProjectsProjectIdRoute,
  } as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminUsersUserIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRouteWithChildren
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRouteWithChildren
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
  '/admin/tickets/new': typeof AdminTicketsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/admin/users/new': typeof AdminUsersNewRoute
  '/portal/projects/$projectId': typeof PortalProjectsProjectIdRoute
  '/portal/tickets/$ticketId': typeof PortalTicketsTicketIdRoute
  '/portal/tickets/new': typeof PortalTicketsNewRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/portal/projects/': typeof PortalProjectsIndexRoute
  '/portal/tickets/': typeof PortalTicketsIndexRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/projects/$projectId/edit': typeof AdminProjectsProjectIdEditRoute
  '/admin/projects/$projectId/members': typeof AdminProjectsProjectIdMembersRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRouteWithChildren
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRouteWithChildren
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
  '/admin/tickets/new': typeof AdminTicketsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/admin/users/new': typeof AdminUsersNewRoute
  '/portal/projects/$projectId': typeof PortalProjectsProjectIdRoute
  '/portal/tickets/$ticketId': typeof PortalTicketsTicketIdRoute
  '/portal/tickets/new': typeof PortalTicketsNewRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/tickets': typeof AdminTicketsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/portal/projects': typeof PortalProjectsIndexRoute
  '/portal/tickets': typeof PortalTicketsIndexRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/projects/$projectId/edit': typeof AdminProjectsProjectIdEditRoute
  '/admin/projects/$projectId/members': typeof AdminProjectsProjectIdMembersRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRouteWithChildren
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRouteWithChildren
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
  '/admin/tickets/new': typeof AdminTicketsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/admin/users/new': typeof AdminUsersNewRoute
  '/portal/projects/$projectId': typeof PortalProjectsProjectIdRoute
  '/portal/tickets/$ticketId': typeof PortalTicketsTicketIdRoute
  '/portal/tickets/new': typeof PortalTicketsNewRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/portal/projects/': typeof PortalProjectsIndexRoute
  '/portal/tickets/': typeof PortalTicketsIndexRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/projects/$projectId/edit': typeof AdminProjectsProjectIdEditRoute
  '/admin/projects/$projectId/members': typeof AdminProjectsProjectIdMembersRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/change-password'
    | '/forgot-password'
    | '/help'
    | '/profile'
    | '/reset-password'
    | '/unauthorized'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/team'
    | '/client/dashboard'
    | '/portal/notifications'
    | '/staff/dashboard'
    | '/admin/'
    | '/portal/'
    | '/admin/customers/$customerId'
    | '/admin/customers/new'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/tickets/$ticketId'
    | '/admin/tickets/new'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/portal/projects/$projectId'
    | '/portal/tickets/$ticketId'
    | '/portal/tickets/new'
    | '/admin/customers/'
    | '/admin/projects/'
    | '/admin/tickets/'
    | '/admin/users/'
    | '/portal/projects/'
    | '/portal/tickets/'
    | '/admin/customers/$customerId/edit'
    | '/admin/projects/$projectId/edit'
    | '/admin/projects/$projectId/members'
    | '/admin/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/change-password'
    | '/forgot-password'
    | '/help'
    | '/profile'
    | '/reset-password'
    | '/unauthorized'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/team'
    | '/client/dashboard'
    | '/portal/notifications'
    | '/staff/dashboard'
    | '/admin'
    | '/portal'
    | '/admin/customers/$customerId'
    | '/admin/customers/new'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/tickets/$ticketId'
    | '/admin/tickets/new'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/portal/projects/$projectId'
    | '/portal/tickets/$ticketId'
    | '/portal/tickets/new'
    | '/admin/customers'
    | '/admin/projects'
    | '/admin/tickets'
    | '/admin/users'
    | '/portal/projects'
    | '/portal/tickets'
    | '/admin/customers/$customerId/edit'
    | '/admin/projects/$projectId/edit'
    | '/admin/projects/$projectId/members'
    | '/admin/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/change-password'
    | '/forgot-password'
    | '/help'
    | '/profile'
    | '/reset-password'
    | '/unauthorized'
    | '/admin/audit'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/team'
    | '/client/dashboard'
    | '/portal/notifications'
    | '/staff/dashboard'
    | '/admin/'
    | '/portal/'
    | '/admin/customers/$customerId'
    | '/admin/customers/new'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/tickets/$ticketId'
    | '/admin/tickets/new'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/portal/projects/$projectId'
    | '/portal/tickets/$ticketId'
    | '/portal/tickets/new'
    | '/admin/customers/'
    | '/admin/projects/'
    | '/admin/tickets/'
    | '/admin/users/'
    | '/portal/projects/'
    | '/portal/tickets/'
    | '/admin/customers/$customerId/edit'
    | '/admin/projects/$projectId/edit'
    | '/admin/projects/$projectId/members'
    | '/admin/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRouteWithChildren
  AdminCustomersNewRoute: typeof AdminCustomersNewRoute
  AdminProjectsProjectIdRoute: typeof AdminProjectsProjectIdRouteWithChildren
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminTicketsTicketIdRoute: typeof AdminTicketsTicketIdRoute
  AdminTicketsNewRoute: typeof AdminTicketsNewRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRouteWithChildren
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  PortalProjectsProjectIdRoute: typeof PortalProjectsProjectIdRoute
  PortalTicketsTicketIdRoute: typeof PortalTicketsTicketIdRoute
  PortalTicketsNewRoute: typeof PortalTicketsNewRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminTicketsIndexRoute: typeof AdminTicketsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  PortalProjectsIndexRoute: typeof PortalProjectsIndexRoute
  PortalTicketsIndexRoute: typeof PortalTicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/portal/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/admin/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/new': {
      id: '/admin/customers/new'
      path: '/admin/customers/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminCustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$projectId': {
      id: '/admin/projects/$projectId'
      path: '/admin/projects/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/admin/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets/': {
      id: '/admin/tickets/'
      path: '/admin/tickets'
      fullPath: '/admin/tickets/'
      preLoaderRoute: typeof AdminTicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets/$ticketId': {
      id: '/admin/tickets/$ticketId'
      path: '/admin/tickets/$ticketId'
      fullPath: '/admin/tickets/$ticketId'
      preLoaderRoute: typeof AdminTicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets/new': {
      id: '/admin/tickets/new'
      path: '/admin/tickets/new'
      fullPath: '/admin/tickets/new'
      preLoaderRoute: typeof AdminTicketsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/new': {
      id: '/admin/users/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/projects/': {
      id: '/portal/projects/'
      path: '/portal/projects'
      fullPath: '/portal/projects/'
      preLoaderRoute: typeof PortalProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/projects/$projectId': {
      id: '/portal/projects/$projectId'
      path: '/portal/projects/$projectId'
      fullPath: '/portal/projects/$projectId'
      preLoaderRoute: typeof PortalProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/tickets/': {
      id: '/portal/tickets/'
      path: '/portal/tickets'
      fullPath: '/portal/tickets/'
      preLoaderRoute: typeof PortalTicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/tickets/$ticketId': {
      id: '/portal/tickets/$ticketId'
      path: '/portal/tickets/$ticketId'
      fullPath: '/portal/tickets/$ticketId'
      preLoaderRoute: typeof PortalTicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/tickets/new': {
      id: '/portal/tickets/new'
      path: '/portal/tickets/new'
      fullPath: '/portal/tickets/new'
      preLoaderRoute: typeof PortalTicketsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$customerId/edit': {
      id: '/admin/customers/$customerId/edit'
      path: '/edit'
      fullPath: '/admin/customers/$customerId/edit'
      preLoaderRoute: typeof AdminCustomersCustomerIdEditRouteImport
      parentRoute: typeof AdminCustomersCustomerIdRoute
    }
    '/admin/projects/$projectId/edit': {
      id: '/admin/projects/$projectId/edit'
      path: '/edit'
      fullPath: '/admin/projects/$projectId/edit'
      preLoaderRoute: typeof AdminProjectsProjectIdEditRouteImport
      parentRoute: typeof AdminProjectsProjectIdRoute
    }
    '/admin/projects/$projectId/members': {
      id: '/admin/projects/$projectId/members'
      path: '/members'
      fullPath: '/admin/projects/$projectId/members'
      preLoaderRoute: typeof AdminProjectsProjectIdMembersRouteImport
      parentRoute: typeof AdminProjectsProjectIdRoute
    }
    '/admin/users/$userId/edit': {
      id: '/admin/users/$userId/edit'
      path: '/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
  }
}

interface AdminCustomersCustomerIdRouteChildren {
  AdminCustomersCustomerIdEditRoute: typeof AdminCustomersCustomerIdEditRoute
}

const AdminCustomersCustomerIdRouteChildren: AdminCustomersCustomerIdRouteChildren =
  {
    AdminCustomersCustomerIdEditRoute: AdminCustomersCustomerIdEditRoute,
  }

const AdminCustomersCustomerIdRouteWithChildren =
  AdminCustomersCustomerIdRoute._addFileChildren(
    AdminCustomersCustomerIdRouteChildren,
  )

interface AdminProjectsProjectIdRouteChildren {
  AdminProjectsProjectIdEditRoute: typeof AdminProjectsProjectIdEditRoute
  AdminProjectsProjectIdMembersRoute: typeof AdminProjectsProjectIdMembersRoute
}

const AdminProjectsProjectIdRouteChildren: AdminProjectsProjectIdRouteChildren =
  {
    AdminProjectsProjectIdEditRoute: AdminProjectsProjectIdEditRoute,
    AdminProjectsProjectIdMembersRoute: AdminProjectsProjectIdMembersRoute,
  }

const AdminProjectsProjectIdRouteWithChildren =
  AdminProjectsProjectIdRoute._addFileChildren(
    AdminProjectsProjectIdRouteChildren,
  )

interface AdminUsersUserIdRouteChildren {
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRoute
}

const AdminUsersUserIdRouteChildren: AdminUsersUserIdRouteChildren = {
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRoute,
}

const AdminUsersUserIdRouteWithChildren =
  AdminUsersUserIdRoute._addFileChildren(AdminUsersUserIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRouteWithChildren,
  AdminCustomersNewRoute: AdminCustomersNewRoute,
  AdminProjectsProjectIdRoute: AdminProjectsProjectIdRouteWithChildren,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminTicketsTicketIdRoute: AdminTicketsTicketIdRoute,
  AdminTicketsNewRoute: AdminTicketsNewRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRouteWithChildren,
  AdminUsersNewRoute: AdminUsersNewRoute,
  PortalProjectsProjectIdRoute: PortalProjectsProjectIdRoute,
  PortalTicketsTicketIdRoute: PortalTicketsTicketIdRoute,
  PortalTicketsNewRoute: PortalTicketsNewRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminTicketsIndexRoute: AdminTicketsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  PortalProjectsIndexRoute: PortalProjectsIndexRoute,
  PortalTicketsIndexRoute: PortalTicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
